version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    target-branch: main
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - github-actions
    commit-message:
      prefix: ci
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: /todo-app
    schedule:
      interval: weekly
    target-branch: main
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - npm
    commit-message:
      prefix: deps

  - package-ecosystem: gomod
    directory: /bff
    schedule:
      interval: weekly
    target-branch: main
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - go
    commit-message:
      prefix: deps

  - package-ecosystem: gomod
    directory: /user-service
    schedule:
      interval: weekly
    target-branch: main
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - go
    commit-message:
      prefix: deps

  - package-ecosystem: gomod
    directory: /todo-service
    schedule:
      interval: weekly
    target-branch: main
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - go
    commit-message:
      prefix: deps

  - package-ecosystem: docker
    directory: /nginx
    schedule:
      interval: weekly
    target-branch: main
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - docker
    commit-message:
      prefix: deps

  - package-ecosystem: docker
    directory: /bff
    schedule:
      interval: weekly
    target-branch: main
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - docker
    commit-message:
      prefix: deps

  - package-ecosystem: docker
    directory: /user-service
    schedule:
      interval: weekly
    target-branch: main
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - docker
    commit-message:
      prefix: deps

  - package-ecosystem: docker
    directory: /todo-service
    schedule:
      interval: weekly
    target-branch: main
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - docker
    commit-message:
      prefix: deps

  - package-ecosystem: docker
    directory: /todo-app
    schedule:
      interval: weekly
    target-branch: main
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - docker
    commit-message:
      prefix: deps
